class IngredientDisplayNames {
  IngredientDisplayNames._();

  // Canonical keyword → locale → display name for translated ingredient chips.
  // Falls back to the canonical English key when a locale is absent.
  static const Map<String, Map<String, String>> names = {
    'alcohol': {
      'de': 'Alkohol',
      'tr': 'alkol',
      'fr': 'alcool',
      'es': 'alcohol',
      'it': 'alcol',
      'nl': 'alcohol',
      'sr': 'alkohol',
      'hu': 'alkohol',
      'cs': 'alkohol',
    },
    'ethanol': {
      'de': 'Äthanol',
      'tr': 'etanol',
      'fr': 'éthanol',
      'es': 'etanol',
      'it': 'etanolo',
      'nl': 'ethanol',
      'sr': 'etanol',
      'hu': 'etanol',
      'cs': 'etanol',
    },
    'wine': {
      'de': 'Wein',
      'tr': 'şarap',
      'fr': 'vin',
      'es': 'vino',
      'it': 'vino',
      'nl': 'wijn',
      'sr': 'vino',
      'hu': 'bor',
      'cs': 'víno',
    },
    'beer': {
      'de': 'Bier',
      'tr': 'bira',
      'fr': 'bière',
      'es': 'cerveza',
      'it': 'birra',
      'nl': 'bier',
      'sr': 'pivo',
      'hu': 'sör',
      'cs': 'pivo',
    },
    'cognac': {
      'de': 'Kognak',
      'tr': 'konyak',
      'sr': 'konjak',
      'hu': 'konyak',
      'cs': 'koňak',
    },
    'brandy': {'de': 'Weinbrand', 'nl': 'brandewijn'},
    'whisky': {'tr': 'viski'},
    'vodka': {'de': 'Wodka', 'sr': 'votka'},
    'rum': {'fr': 'rhum', 'es': 'ron'},
    'gin': {'sr': 'džin'},
    'liqueur': {
      'de': 'Likör',
      'fr': 'liqueur',
      'es': 'licor',
      'it': 'liquore',
      'nl': 'likeur',
      'sr': 'liker',
      'hu': 'likőr',
      'cs': 'likér',
    },
    'schnapps': {'de': 'Schnaps', 'sr': 'šnaps'},
    'champagne': {
      'de': 'Sekt',
      'es': 'cava',
      'it': 'spumante',
      'sr': 'šampanjac',
      'hu': 'pezsgő',
      'cs': 'šampaňské',
    },
    'pork': {
      'de': 'Schweinefleisch',
      'tr': 'domuz',
      'fr': 'porc',
      'es': 'cerdo',
      'it': 'maiale',
      'nl': 'varkensvlees',
      'sr': 'svinjetina',
      'hu': 'sertéshús',
      'cs': 'vepřové',
    },
    'lard': {
      'de': 'Schmalz',
      'tr': 'domuz yağı',
      'fr': 'saindoux',
      'es': 'manteca de cerdo',
      'it': 'strutto',
      'sr': 'svinjska mast',
      'hu': 'sertészsír',
      'cs': 'sádlo',
    },
    'gelatin': {
      'de': 'Gelatine',
      'tr': 'jelatin',
      'fr': 'gélatine',
      'es': 'gelatina',
      'it': 'gelatina',
      'sr': 'želatina',
      'hu': 'zselatin',
      'cs': 'želatina',
    },
    'bacon': {
      'de': 'Speck',
      'tr': 'domuz pastırması',
      'fr': 'lardons',
      'it': 'pancetta',
      'sr': 'slanina',
      'hu': 'szalonna',
      'cs': 'slanina',
    },
    'ham': {
      'de': 'Schinken',
      'fr': 'jambon',
      'es': 'jamón',
      'it': 'prosciutto',
      'nl': 'ham',
      'sr': 'šunka',
      'hu': 'sonka',
      'cs': 'šunka',
    },
    'salami': {'it': 'salame', 'hu': 'szalámi', 'cs': 'salám'},
    'carmine': {
      'de': 'Karmin',
      'tr': 'karmin',
      'fr': 'carmin',
      'es': 'carmín',
      'sr': 'karmin',
      'hu': 'karmin',
      'cs': 'karmin',
    },
    'cochineal': {
      'de': 'Cochenille',
      'tr': 'koşnil',
      'fr': 'cochenille',
      'es': 'cochinilla',
      'it': 'cocciniglia',
      'sr': 'košenil',
      'cs': 'košenila',
    },
    'rennet': {
      'de': 'Lab',
      'tr': 'peynir mayası',
      'fr': 'présure',
      'es': 'cuajo',
      'it': 'caglio',
      'nl': 'stremsel',
      'sr': 'sirilo',
      'hu': 'oltóanyag',
      'cs': 'syřidlo',
    },
    'whey': {
      'de': 'Molke',
      'tr': 'peynir suyu',
      'fr': 'lactosérum',
      'es': 'suero de leche',
      'it': 'siero di latte',
      'nl': 'wei',
      'sr': 'surutka',
      'hu': 'tejsavó',
      'cs': 'syrovátka',
    },
    'l-cysteine': {
      'de': 'L-Cystein',
      'tr': 'l-sistein',
      'fr': 'l-cystéine',
      'es': 'l-cisteina',
      'it': 'l-cisteina',
      'sr': 'l-cistein',
      'hu': 'l-cisztein',
      'cs': 'l-cystein',
    },
    'natural flavour': {
      'de': 'natürliches Aroma',
      'tr': 'doğal aroma',
      'fr': 'arôme naturel',
      'es': 'aroma natural',
      'it': 'aroma naturale',
      'nl': 'natuurlijk aroma',
      'sr': 'prirodna aroma',
      'hu': 'természetes aroma',
      'cs': 'přírodní aroma',
    },
    'flavouring': {
      'de': 'Aroma',
      'tr': 'aroma',
      'fr': 'arôme',
      'nl': 'smaakstof',
      'hu': 'ízesítő',
    },
    'enzymes': {
      'de': 'Enzyme',
      'tr': 'enzim',
      'es': 'enzimas',
      'it': 'enzimi',
      'nl': 'enzymen',
      'sr': 'enzimi',
      'hu': 'enzim',
      'cs': 'enzymy',
    },
    'glycerol': {
      'de': 'Glycerin',
      'tr': 'gliserin',
      'fr': 'glycérol',
      'es': 'glicerina',
      'it': 'glicerina',
      'nl': 'glycerine',
      'sr': 'glicerol',
    },
  };

  static String of(String canonical, String locale) =>
      names[canonical]?[locale] ?? canonical;
}
